# Generated by Django 3.2.8 on 2021-10-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_portfolio_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='last_adjusted',
            field=models.DateField(auto_now=True),
        ),
    ]
